# Networking
IP="0.0.0.0"
PORT="28015"
QUERYPORT="28017"
RCONPORT="28016"
APPORT="28082"

# RCON
RCONPASSWORD="CHANGE_ME"
RCONWEB="1"

# Server identity
SERVERNAME="[EU] Rustux | Wednesday | Linux, Steam Deck & Windows"
SERVERDESCRIPTION="Welcome to [EU] Rustux, the Vanilla server for Linux, Steam Deck & Windows Players!

General information:
➤ Linux, Steam Deck and Windows
➤ Vanilla: No mods, no pay-to-win
➤ Wipe schedule: Monthly @ Force
➤ Map size: 4000
➤ Join Discord: discord.gg/Y3atKERBpK
➤ Group limit: 5
➤ Admins not playing and active
➤ Bare metal server, low latency, and smooth gameplay

Rules:
1. No Cheating or Exploiting
2. No Toxicity or Harassment
3. Fair PVP
4. Building Restrictions
5. Respect Server Performance
6. No Abusing Game Mechanics"

SELFNAME="rustux"
GAMEMODE="hardcore"
SERVERLEVEL="Procedural Map"

# World
SEED="1930813691"
SALT=""
WORLDSIZE="4000"

# Gameplay
MAXPLAYERS="100"
SAVEINTERVAL="300"
TICKRATE="30"
TAGS="hardcore,vanilla,EU"

# Logging
GAMELOG="/var/lib/rust/server/logs/server.log"
